---
- name: Install Jenkins on Ubuntu
  hosts: jenkins_servers
  become: yes

  tasks:
    - name: Add Jenkins repository and key
      apt_repository:
        repo: deb http://pkg.jenkins.io/debian binary/
        state: present
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
