- name: Setup Sonarqube On Sonarqube CI Server
  hosts: jenkins_servers
  become_method: sudo
  become: true
  vars_files:
    - "sonar_q_variables.yml"
  gather_facts: true

  tasks:
    - name: Ensure passlib is installed
      pip:
        name: passlib
        state: present
        executable: pip3